name = "squawk-dns-website"
compatibility_date = "2024-01-15"

# Pages configuration
[env.production]
name = "squawk-dns-website"
compatibility_date = "2024-01-15"

# Build configuration for Pages
[build]
command = "npm install && npm run build"
cwd = ""

# Static site configuration
[[pages_build_output_dir]]
# For static sites, this would be the build output directory
# Since this is a Node.js app, we'll use the entire directory
value = "."

# Environment variables for production
[vars]
NODE_ENV = "production"
PORT = "8080"

# Development environment
[env.development]
name = "squawk-dns-website-dev"
compatibility_date = "2024-01-15"

[env.development.vars]
NODE_ENV = "development"
PORT = "3000"

# Pages deployment settings
[pages]
# Build configuration
build_command = "npm install && npm start"
build_output_dir = "."
# Node.js compatibility for Cloudflare Pages
compatibility_flags = ["nodejs_compat"]

# Custom domains (update as needed)
# custom_domains = ["squawkdns.com", "www.squawkdns.com"]

# Headers for security and performance
[[pages.headers]]
for = "/*"
[pages.headers.values]
"X-Frame-Options" = "DENY"
"X-Content-Type-Options" = "nosniff"
"Referrer-Policy" = "strict-origin-when-cross-origin"
"Permissions-Policy" = "camera=(), microphone=(), geolocation=()"

[[pages.headers]]
for = "/css/*"
[pages.headers.values]
"Cache-Control" = "public, max-age=31536000, immutable"

[[pages.headers]]
for = "/js/*"
[pages.headers.values]
"Cache-Control" = "public, max-age=31536000, immutable"

[[pages.headers]]
for = "/images/*"
[pages.headers.values]
"Cache-Control" = "public, max-age=31536000, immutable"

# Redirects
[[pages.redirects]]
from = "/docs"
to = "/documentation"
status = 301

[[pages.redirects]]
from = "/github"
to = "https://github.com/penguincloud/squawk"
status = 302