name = "squawk-dns-website"
main = "server.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[vars]
NODE_ENV = "production"
PORT = "8080"

# Production environment
[env.production]
name = "squawk-dns-website"
compatibility_date = "2024-01-15"

[env.production.vars]
NODE_ENV = "production"
PORT = "8080"

# Development environment
[env.dev]
name = "squawk-dns-website-dev"
compatibility_date = "2024-01-15"

[env.dev.vars]
NODE_ENV = "development"
PORT = "3000"

# Build configuration
[build]
command = "npm install"