# Cloudflare Pages configuration
# Note: Build settings should be configured in Cloudflare dashboard:
# - Build command: npm run build
# - Build output directory: out
# - Root directory: website

name = "squawk-dns-website"
compatibility_date = "2024-01-15"

# Headers for security and performance
[[headers]]
for = "/*"
[headers.values]
"X-Frame-Options" = "DENY"
"X-Content-Type-Options" = "nosniff"
"Referrer-Policy" = "strict-origin-when-cross-origin"
"Permissions-Policy" = "camera=(), microphone=(), geolocation=()"

[[headers]]
for = "/favicon.ico"
[headers.values]
"Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
for = "/_next/static/*"
[headers.values]
"Cache-Control" = "public, max-age=31536000, immutable"

# Redirects
[[redirects]]
from = "/docs"
to = "/documentation"
status = 301

[[redirects]]
from = "/github"
to = "https://github.com/penguincloud/squawk"
status = 302