name = "squawk-dns-website"
compatibility_date = "2024-01-15"

# Environment variables for production
[vars]
NODE_ENV = "production"
PORT = "8080"

# Production environment
[env.production]
name = "squawk-dns-website"
compatibility_date = "2024-01-15"

[env.production.vars]
NODE_ENV = "production"
PORT = "8080"

# Preview environment
[env.preview]
name = "squawk-dns-website-preview"
compatibility_date = "2024-01-15"

[env.preview.vars]
NODE_ENV = "development"
PORT = "3000"