name = "squawk-dns-website"
compatibility_date = "2024-01-15"

# Build configuration for Pages
pages_build_output_dir = "."

# Environment variables for production
[vars]
NODE_ENV = "production"
PORT = "8080"

# Production environment
[env.production]
name = "squawk-dns-website"
compatibility_date = "2024-01-15"

[env.production.vars]
NODE_ENV = "production"
PORT = "8080"

# Development environment
[env.development]
name = "squawk-dns-website-dev"
compatibility_date = "2024-01-15"

[env.development.vars]
NODE_ENV = "development"
PORT = "3000"