name = "squawk-dns-website"
compatibility_date = "2024-01-15"

# Build configuration
[build]
command = "cd website && npm install && npm run build"
cwd = ""

# Environment variables
[vars]
NODE_ENV = "production"

# Production environment
[env.production]
name = "squawk-dns-website"

[env.production.vars] 
NODE_ENV = "production"

# Preview environment
[env.preview]
name = "squawk-dns-website-preview"

[env.preview.vars]
NODE_ENV = "development"