name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          gcc \
          g++ \
          libxml2-dev \
          libxslt1-dev \
          libldap-dev \
          libldap2-dev \
          libsasl2-dev \
          python3-dev \
          pkg-config
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        # Try full installation first
        pip install -r dns-server/requirements.txt || \
        (echo "::warning::Enterprise features installation failed, using base requirements" && \
         pip install -r dns-server/requirements-base.txt)
    
    - name: Run tests
      run: |
        python -m pytest dns-server/tests/ -v
    
  docker-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: |
        docker build -t squawk-dns:test .
    
    - name: Test Docker image
      run: |
        docker run --rm squawk-dns:test python --version
        docker run --rm squawk-dns:test python -c "import dns.resolver; print('DNS module OK')"